### ISSUE TITLE
[carrier-integration] DHL eCommerce Germany - Get Rates and Buy Label

### ISSUE THREAD

**Issue by danh91** [karrioapi/karrio#119]
**Is your feature request related to a problem? Please describe.**

It is currently possible to track shipments serviced by `DHL Universal`. I did like to be able to the purplship SDK 
fetch live rates for shipments everywhere DHL eCommerce is available and buy labels.

**Comment by MarcoWel** [comment]
DHL eCommerce is crucial for us as well. Can we support you implementing it?

**Comment by MarcoWel** [comment]
Thank you for the quick reply. I can let you know that around 9 out of 10 companies in Germany ship with DHL, so getting that API supported will definitely help Purplship to gain popularity here.

How much would it cost to sponsor this integration?

The DHL Docs are good and easy to read:
https://api-sandbox.dhlecommerce.com/apidoc/apidoc-label.html

There are two PHP implementations for the DHL API already which can be taken as a reference, it is quite straightforward to implement:
- https://github.com/Petschko/dhl-php-sdk
- https://github.com/mvdnbrk/dhlparcel-php-api

**Comment by MarcoWel** [comment]
Hi,
We currently use the SDK only to do automated address validation when an order comes in. The label creation and shipment tracking is currently handled by our ERP system.

We are moving to a new ERP solution and would like to have a separate, central and independent system for address verification, label creation and live tracking across all our carriers (DHL, DHL Express, UPS). There are plenty of SaaS providers for exactly that, but we would prefer our own solution regarding GDPR and cost (yes, a few cents per package accumulates to a lot of additional cost).

Purplship seems like the perfect fit for our needs, and as far as I could see, the only open-source solution out there. So yes, we would love to use and support the Purplship project!

**Comment by MarcoWel** [comment]
Hey @danh91,
Any update on the current implementation? Please let me know if we could help out in any way.

**Comment by danh91** [comment]
Hi @MarcoWel,

I, unfortunately, couldn't get to finish the integration due to an unforeseen load of support tickets that we received.

In all transparency, sponsoring the integration helps us hire the necessary help to accelerate integrations then
we do the QA and add it to the project. 
It's a one-time fee and we continue the maintenance and updates as long as it is relevant to you and any other user in the community.

Feel free to DM me at hello@purplship.com or on [Discord](https://discord.gg/gS88uE7sEx) if you can sponsor.

Thanks
