### ISSUE TITLE
Update Tracking event response to have a separate object for location.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [karrioapi/karrio#180]
Currently, the tracking event contains a single key for the location information on each event.

```json
{
      ... tracking details
      "events": [
        {
          "date": "string",
          "description": "string",
          "location": "string",
          "code": "string",
          "time": "string"
        }
      ],
      ... deliver details
    }
  ]
}
```

This will need to be a separate object to have more information about the location of the event.

```json
{
      ... tracking details
      "events": [
        {
          "date": "string",
          "description": "string",
          "location": {
                "city": "string",
                "state": "string",
                "zipcode": "string",
                "country": "string",
                "geocoding": {
                      "latitude": "string",
                      "longitude": "string",
                }
           },
          "code": "string",
          "time": "string"
        }
      ],
      ... deliver details
    }
  ]
}

```

The geocoding object can be done through either open-source integrations with geonames.org or through proprietary integrations like Google Geocoding or Maxmind databases. Based on how it is hosted.

**Comment by danh91** [comment]
Thanks for this @abishekrsrikaanth ,

If I understand one interesting use case with that is the ability to show on a map the real-time location of the package right?
