### ISSUE TITLE
Trade documents upload API

### ISSUE THREAD

**Issue by mars0001** [karrioapi/karrio#191]
Hello, 
I apologize if this is answered elsewhere, I did made a search but I may have overlooked it. I am new to `purplship` and also still trying to understand the concepts behind shipping API's.

**Is your feature request related to a problem? Please describe.**
I wonder if the upload of trade documents is supported by the `purplship` package. I could find no reference in the documentation.

**Describe the solution you'd like**
I am looking for a implementation of what it is described here:
https://developertest.fedex.com/api/en-nl/catalog/upload-documents/v1/docs.html

Thank you for all the efforts put in this package!!! I **do** know how much time it takes...

**Comment by danh91** [comment]
Hi @mars0001,

No need for apologies. I am glad you discovered `purplship`.

Unfortunately, though, at this point, the package doesn't support the FedEx upload documents API.

Thanks

**Comment by mars0001** [comment]
Hi Daniel @danh91 ,

Thank you for your kind answer! I hope to see this added, it will add more value to `purplship`.

Best regards,
Marius

**Comment by danh91** [comment]
I will close this issue for now. And link it to a PR when we tackle documents API integration
