### ISSUE TITLE
Carriers without rates API: Support for loading rate price lists / Setting rates by service, country and weight

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#319]
**Is your feature request related to a problem? Please describe.**
Some carriers like DPDHL do not support fetching rates via API. But we get rate tables every year (CSV format).
The rates depend on service, destination country and shipping weight. Currently, it is not possible to get proper rates from karrio for these carriers.

**Describe the solution you'd like**
Please make it possible to support those more complex rate tables. Maybe you make the rates configurable via a free-text json field for the carrier to set "extended rate configuration"? This way, we can convert a dedicated rate table to your json format ourselves and copy/paste it to the dashboard once per year. Plus you save complex import functionality or tedious manual settings in the dashboard.

**Describe alternatives you've considered**
None. Rates must be precise for all carriers.

**Additional context**
Current dashboard settings (only allow rates per service):

![image](https://user-images.githubusercontent.com/80592577/220319924-19266547-f77b-4cec-97ff-c04661813983.png)

**Comment by MarcoWel** [comment]
Suggested JSON formats:

**Variant 1:**
```json
{
    "DHL Paket": {
        "DE": {
            "1.0": 3.80,
            "10.0": 6.50,
            "31.5": 7.90
        }
    },
    "DHL Europaket": {
        "FR": {
            "31.5": 10.90
        },
        "NL": {
            "10.0": 8.90,
            "31.5": 10.50
        },
        ...
    },
    ...
}
```

**Variant 2:**
```json
[
    {
        "service": "DHL Paket",
        "rates": [
            {
                "countryCodes": ["DE"],
                "maxWeight": 1.0,
                "rate": 3.80
            },
            {
                "countryCodes": ["DE"],
                "maxWeight": 10.0,
                "rate": 6.50,
            },
            {
                "countryCodes": ["DE"],
                "maxWeight": 31.5,
                "rate": 7.90
            }
        ]
    },
    {
        "service": "DHL Europaket",
        "rates": [
            {
                "countryCodes": ["FR"],
                "maxWeight": 31.5,
                "rate": 10.90
            },
            {
                "countryCodes": ["NL"],
                "maxWeight": 10.0,
                "rate": 8.90,
            },
            {
                "countryCodes": ["NL"],
                "maxWeight": 31.5,
                "rate": 10.50
            },
            {
                "countryCodes": ["SE", "FI"],
                "maxWeight": 31.5,
                "rate": 12.50
            },
            ...
        ]
    },
    ...
]

```

**Comment by danh91** [comment]
Thanks, @MarcoWel, This is a great breakdown.
This is a great iteration forward for the static rate list.

Can you please share the links for the rate list of DPDHL?

I want to take the opportunity to study 2 or 3 other carriers' rate sheets to update and improve the current abstraction.

**Comment by MarcoWel** [comment]
They usually provide a PDF, I will check if I can forward you something as XLSX.

**Comment by MarcoWel** [comment]
I looked it up, DHL customers just get the pricing as PDF. There are two pricing types:

- National: Fixed pricing brackets for a service, e.g. up to 1kg, up to 10kg, up to 31.5kg
- International: Destinations grouped by zones. For each zone, there is a base price + a price per kg

A pricing table for international shipping can look like this:

![image](https://user-images.githubusercontent.com/80592577/223972972-7c407abd-5fb0-4a0e-82af-507ab64e5a3f.png)

**Comment by MarcoWel** [comment]
I would implement it like this:

- Zone table per carrier: simple JSON for creating the zones
- Pricing table per carrier: simple JSON for  pricing per service and zone, with a base price and weight price (per kg)

With this schema, almost all carrier pricing schemes can be handled.

My suggestion would be a text box under "Extended Info" where the plain JSON can be entered (with a default pre-defined scheme). This way, the JSON code can be generated externally and then just copy&pasted instead of handling dozens of GUI controls.

**Zones:**
```
[
    {
        "zone": "National",
        "countryCodes": ["DE"]
    },
    {
        "zone": "1 EU",
        "countryCodes": ["NL", "AT", ...]
    },
    {
        "zone": "1 NON-EU",
        "countryCodes": ["CH", ...]
    },
    ...
]
```

**Rates:**
```
[
    {
        "service": "DHL Paket",
        "productCode": "V01PAK",
        "billingCode": "0101",
        "rates": [
            {
                "zone": "National",
                "maxWeight": 1.0,
                "basePrice": 3.80,
                "weightPrice": 0.00
            },
            {
                "zone": "National",
                "maxWeight": 10.0,
                "basePrice": 6.50,
                "weightPrice": 0.00
            },
            {
                "zone": "National",
                "maxWeight": 31.7,
                "basePrice": 7.90,
                "weightPrice": 0.00
            }
        ]
    },
    {
        "service": "DHL Paket International Premium",
        "productCode": "W53PAK",
        "billingCode": "5301",
        "rates": [
            {
                "zone": "1 EU",
                "maxWeight": 31.5,
                "basePrice": 10.90,
                "weightPrice": 0.80
            },            
            ...
        ]
    },
    ...
]
```

In the code examples, I also added the necessary fields for issue #333 ;)

**Comment by danh91** [comment]
We've made some progress on this.

Currently, though the Service Level Definition only shows this:
![image](https://user-images.githubusercontent.com/80592577/220319924-19266547-f77b-4cec-97ff-c04661813983.png)

On the API level, Karrio has something like this
```json
[
    {
        "id": "",
        "service_name": "",
        "service_code": "",
        "description": "",
        "active": true,
        "cost": 0.0,
        "currency": "EUR",
        "estimated_transit_days": 1,
        "max_weight": null,
        "max_width": null,
        "max_height": null,
        "max_length": null,
        "weight_unit": "KG",
        "dimension_unit": "CM",
        "domicile": true,
        "international": true
    }
]
```

As you brought up. The problem here is that the service only has one `rate` which is not enough.
So we are moving toward something like this instead

```json
[
    {
        "object_type": "service",
        "id": "",
        "service_name": "",
        "service_code": "",
        "description": "",
        "active": true,
        "currency": "EUR",
        "estimated_transit_days": 1,
        "max_weight": null,
        "min_weight": null,
        "max_width": null,
        "max_height": null,
        "max_length": null,
        "weight_unit": "KG",
        "dimension_unit": "CM",
        "domicile": true,
        "international": true,
-        "cost": 0.0,
        "zones": [
            {
                "object_type": "zone",
                "rate": 0.0,
                "max_weight": null,
                "min_weight": null,
                "cities": [""],
                "country_codes": ["DE","FR"]
            }
        ]
    }
]
```

The idea is to have something that can abstract any carrier rate sheet and Karrio use that to provide static `rates`.

So rates are created using the service details + the zone charges (rates, + any additional in the future)

**Comment by MarcoWel** [comment]
Sounds great! I would suggest to have a separate, global zone definition:
```
[
    {
        "object_type": "zone",
        "id": "DHL-EU-1",
        "description": "DHL Paket Zone EU 1",
        "active": true,
        "cities": [],
        "country_codes": ["NL","FR", ...]
    }
]
```

The zone should be referenced within the API by ID. The transit time should also be within the zone reference, so more accurate transit time can be provided.
```
[
    {
        "object_type": "service",
        "id": "",
        "service_name": "",
        "service_code": "",
        "description": "",
        "active": true,
        "currency": "EUR",
        "estimated_transit_days": 1,
        "max_weight": null,
        "min_weight": null,
        "max_width": null,
        "max_height": null,
        "max_length": null,
        "weight_unit": "KG",
        "dimension_unit": "CM",
        "domicile": true,
        "international": true,
        "rates": [
            {
                "object_type": "rate",
                "zone_id": "DHL-EU-1",
                "rate": 0.0,
                "estimated_transit_days": 1,
                "max_weight": null,
                "min_weight": null,
            }
        ]
    }
]
```

This way, zones can be shared by carrier. If a zone changes, you do not need to readjust every single carrier using that zone.

**Comment by MarcoWel** [comment]
Solved the country_codes issue. cities needs to be changed from null to [] and it works.
Suggest to either have [] by default in the template or to treat [] and null equal in code.
