### ISSUE TITLE
Database env variables don't work in docker-compose.yml

### ISSUE THREAD

**Issue by vladsydor87** [karrioapi/karrio#321]
**Describe the bug**
When I want to add database environments to the module explicitly it doesn't work correctly. I'm using the external database.
Nevertheless, it works well when I use the DATABASE_URL environment.

**To Reproduce**
1. create docker-compose.yml;
2. add env variables (see screenshot below);
3. `docker compose up`;

**Expected behavior**
The app should be connected to the external database and apply migrations.

**Screenshots**
![image](https://user-images.githubusercontent.com/120730480/220929685-91ed198b-e3ff-45e0-95c4-aa1b929c5f73.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (WSL Ubuntu 20.04)

**Comment by danh91** [comment]
Completed with https://github.com/karrioapi/karrio/pull/318
