### ISSUE TITLE
DPDHL: Add postfix to account number depending on product

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#333]
The billing number for DPDHL needs to be the customer account number (EKP) plus a 4-digit code. This code is dependent on the ordered product.

A full list can be seen here:
https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/current/authentifizierung

![image](https://user-images.githubusercontent.com/80592577/223701678-2d1170ae-72a9-4f81-84a3-4a09f3425b28.png)

Without the correct combination of EKP + postfix, the DHL server returns an error 500 (see related issue #314).

Example: In test mode (for the sandbox endpoint), the EKP number always needs to be set to "2222222222".
- When ordering a normal DHL Paket (product code V01PAK), the postfix needs to be "0101". So the account number in the SOAP request is "22222222220101".
- For DHL Paket International (V53WPAK), the postfix needs to be "5301", resulting in account number "22222222225301".

You can check the same issue for the Petschko DHL API here:
https://github.com/Petschko/dhl-php-sdk/issues/28

**Comment by danh91** [comment]
😄 I think that's exactly what was missing

**Comment by MarcoWel** [comment]
The postfix seems to basically just be 2nd/3rd char from the product code ("01" for V**01**PAK) plus 2 digits for pricing category (should be user settable per carrier, "01" most of the time).

See Petschko's code here:
https://github.com/Petschko/dhl-php-sdk/blob/master/includes/ShipmentDetails.php
```
	 * EKP Account Number         (10 Digits) Example 123457890
	 * concat Product Type Number (2 Digits)  Example 01 for V01PAK or 53 for V53WPAK or 07 for Retoure Online
	 * concat Process Type Number (2 Digits)  Example 01 for default or 02 for block pricing/flat fee
	 *                                         = 1234578900101
```

**Comment by MarcoWel** [comment]
@danh91 As a little addition: Other shipping services usually ask the user to define the whole EKP incl. suffix per product group, like this:
![image](https://user-images.githubusercontent.com/80592577/226008708-d7a41014-fa34-4558-8a21-4e385d1672b6.png)

This leaves the suffixes up to the user and allows more flexibility in case the user wants to use different EKP for different services/products.

If karrio just takes one EKP per carrier and adds the suffix automatically, it is more comfortable for the user but might be less flexible.

**Comment by MarcoWel** [comment]
I can confirm this works with DHL Paket within Germany now for label creation.
For shipments outside Germany, I get an error `[ "Request failed with status code 500" ]`

There are no log events in the dashboard. The docker logs reveal the reason though:

```
karrio.api        | DEBUG helpers.py 209 sending request (9d09f901-af7c-4f70-afed-9a1851d9e0be)...
karrio.api        | INFO helpers.py 150 Request URL:: https://cig.dhl.de/services/production/soap
karrio.api        | DEBUG serializable.py 30 <soap:Envelope xmlns:bcs="http://dhl.de/webservices/businesscustomershipping/3.0" xmlns:cis="http://dhl.de/webservice/cisbase" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
karrio.api        |    <soap:Header/>
karrio.api        |    <soap:Body>
karrio.api        |       <bcs:CreateShipmentOrderResponse>
karrio.api        |          <bcs:Version>
karrio.api        |             <majorRelease>3</majorRelease>
karrio.api        |             <minorRelease>4</minorRelease>
karrio.api        |          </bcs:Version>
karrio.api        |          <Status>
karrio.api        |             <statusCode>1101</statusCode>
karrio.api        |             <statusText>Hard validation error occured.</statusText>
karrio.api        |          </Status>
karrio.api        |          <CreationState>
karrio.api        |             <sequenceNumber>1</sequenceNumber>
karrio.api        |             <LabelData>
karrio.api        |                <Status>
karrio.api        |                   <statusCode>1101</statusCode>
karrio.api        |                   <statusText>Hard validation error occured.</statusText>
karrio.api        |                   <statusMessage>Das angegebene Produkt ist nicht bekannt.</statusMessage>
karrio.api        |                   <statusMessage>Die angegebene Straße kann nicht gefunden werden.</statusMessage>
karrio.api        |                   <statusMessage>Der eingegebene Wert ist zu lang und wurde gekürzt.</statusMessage>
karrio.api        |                   <statusMessage>Das angegebene Produkt ist nicht bekannt.</statusMessage>
karrio.api        |                   <statusType>Error</statusType>
karrio.api        |                   <errorMessage>
karrio.api        |                      <statusElement>  
karrio.api        |                 Shipment.ShipmentDetails.product
karrio.api        |             </statusElement>
karrio.api        |                      <statusMessage>Das angegebene Produkt ist nicht bekannt.</statusMessage>
karrio.api        |                   </errorMessage>
karrio.api        |                   <statusType>Warning</statusType>
karrio.api        |                   <warningMessage>
karrio.api        |                      <statusElement>   
karrio.api        |                 Shipment.Shipper.Address.cis:streetName
karrio.api        |             </statusElement>
karrio.api        |                      <statusMessage>Die angegebene Straße kann nicht gefunden werden.</statusMessage>
karrio.api        |                   </warningMessage>
karrio.api        |                   <warningMessage>
karrio.api        |                      <statusElement> 
karrio.api        |                 Shipment.Shipper.Address.cis:streetNumber
karrio.api        |             </statusElement>
karrio.api        |                      <statusMessage>Der eingegebene Wert ist zu lang und wurde gekürzt.</statusMessage>
karrio.api        |                   </warningMessage>
karrio.api        |                </Status>
karrio.api        |             </LabelData>
karrio.api        |          </CreationState>
karrio.api        |       </bcs:CreateShipmentOrderResponse>
karrio.api        |    </soap:Body>
karrio.api        | </soap:Envelope>
karrio.api        | ERROR abstract.py 199 [Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={}), Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={'message': 'Das angegebene Produkt ist nicht bekannt. Die angegebene Straße kann nicht gefunden werden. Der eingegebene Wert ist zu lang und wurde gekürzt. Das angegebene Produkt ist nicht bekannt.', 'error': '  \n                Shipment.ShipmentDetails.product\n            : Das angegebene Produkt ist nicht bekannt.', 'warning': [<dpdhl_lib.business_interface.StatusElement object at 0x7f4f776f8df0>, <dpdhl_lib.business_interface.StatusElement object at 0x7f4f776f8d30>]})]
```

**Comment by MarcoWel** [comment]
@danh91 Just tested with karrio 2023.04.1.01.

- Generic error display from above is still present.
- Label creation works for shipments within DE, but not within EU. I assume this is because karrio adds 0101/5301/5401 postfix hardcoded. We have default pricing within DE (postfix 0101), but block pricing within EU (postfix 5302/5402). Is there a way to set the postfix by service, e.g. in the new JSON settings?

`karrio.api        | karrio.server.core.exceptions.APIException: [Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={}), Message(carrier_name='dpdhl', carrier_id='DHL', message='Hard validation error occured.', code=1101, details={'message': 'Die ausgewählte Abrechnungsnummer steht nicht zur Verfügung. Die angegebene Straße kann nicht gefunden werden. Der eingegebene Wert ist zu lang und wurde gekürzt. Die ausgewählte Abrechnungsnummer steht nicht zur Verfügung. Die ausgewählte Abrechnungsnummer steht nicht zur Verfügung. Bitte beachten Sie, dass der Service Vorausverfügung für Sendungen mit DHL Paket International verpflichtend ist.', 'error': '  \n                ShipmentOrder.Shipment.ShipmentDetails.cis:accountNumber\n            : Die ausgewählte Abrechnungsnummer steht nicht zur Verfügung.   \n                ShipmentOrder.Shipment.ShipmentDetails.cis:accountNumber\n            : Die ausgewählte Abrechnungsnummer steht nicht zur Verfügung.', 'warning': [<dpdhl_lib.business_interface.StatusElement object at 0x7f1b75682980>, <dpdhl_lib.business_interface.StatusElement object at 0x7f1b75680880>, <dpdhl_lib.business_interface.StatusElement object at 0x7f1b75683850>]})]`

**Comment by danh91** [comment]
Can you walk me through some scenarios and edge cases?

Something like:
When `DE` to `DE` with `service`  = > prefix 

From what I understood, the options can also affect the prefix

If by any chance you have something that documents the rules for the prefix further, it might help.

Right now, I am not sure. The whole purpose of the unified API is to handle the carrier-specific logic at the integration level. 

The service objects are not aware of prefixes, it is dpdhl specific. I could expose an option that can take the prefix and you can set it for your shipment as a work around. 

But eventually, when someone else will try to create shipments they won't be able unless they have the same deep understanding as you.

We were hoping to figure out the logic/rules so that all there is to know is to pick a service and Karrio can deduce the prefix.

You can take look at the code. It is not hard coded but more like a function that tries to resolve the prefix. If we can figure that out, it will be a win in simplicity.


Also, in the meantime, as you mentioned, we added the flexibility of defining the prefix when you set up the connection. Essentially if you pass an account number with the prefix already on it. It will be more than 10 digits so Karrio will send the request without adding the prefix.

So you can create a setting for each service that you are interested in with account numbers already prefixed. Then use the new carrier config to only allow that service. That should solve the EU problem.

Let me know what you think

**Comment by MarcoWel** [comment]
Mentioning this for [patch] 2023.4.4 #373

**Comment by danh91** [comment]
Yup this will make it
