### ISSUE TITLE
Carrier API Request: HTTP errors not shown in dashboard request log

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#334]
DPDHL: HTTP Error 500

![image](https://user-images.githubusercontent.com/80592577/223704132-bc8679ed-fac3-42d5-9368-c06d0fb41f18.png)

![image](https://user-images.githubusercontent.com/80592577/223704195-04966648-229f-4f72-887d-d6576e350ec7.png)

Same for DPDHL HTTP Error 401.

See related issue #314

**Comment by danh91** [comment]
I've experienced that with FedEx too. When I get 500 and an empty response body

**Comment by MarcoWel** [comment]
I can confirm the fix. HTTP errors are now displayed correctly.

![image](https://user-images.githubusercontent.com/80592577/226180871-2da8a48e-fe33-42b6-8e23-dd7a9c465d32.png)
