### ISSUE TITLE
DHL Express: Bugs for Domestic Label Creation

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#367]
**Describe the bug**
When creating a domestic DHL Express shipment, there are some oddities within karrio (version 2023.04.1.01):

1. Karrio suggests both Domestic and Worldwide services for a domestic shipment (sender country = receiver country). Only the domestic service works, DHL Express will return an error trying to book the worldwide service.
2. Service addition "10:30 PREMIUM" is always booked (quite costly).
3. Addition "10:30" is displayed as "10 30" in the service name.

**To Reproduce**
1. Go to "Shipments"
2. Enter Sender and Recipient address in the same country (e.g. DE -> DE)
3. Check the offered DHL Express services.

**Expected behavior**
1. Only domestic services should be suggested for domestic shipments.
2. Service addition "10:30 PREMIUM" should be disabled by default. There should be a way to add it optionally.
3. Addition "10:30" should be displayed including the double colon.

**Screenshots**

Normal worldwide service offered for domestic shipment, always including 10:30 service displayed ad "10 30":

![image](https://user-images.githubusercontent.com/80592577/233790362-9fa1cad8-a71e-49b2-a1d2-3d449319ba46.png)

Error when trying to book the normal worldwide service:

![image](https://user-images.githubusercontent.com/80592577/233790566-6b0c3005-e9bf-4be0-b63e-4d51c2942e83.png)

10:30 PREMIUM service shown when successfully booking the domestic shipment:

![image](https://user-images.githubusercontent.com/80592577/233790409-ad70336a-a092-419e-852a-e6f69e2a2c19.png)

**Additional Context**

Full DHL Express rate request response attached:
[dhl_express_rate_req_response.xml.txt](https://github.com/karrioapi/karrio/files/11301562/dhl_express_rate_req_response.xml.txt)

Seems karrio does not show all offered services / service combinations, but only the first and most expensive within a certain service group.

**Comment by MarcoWel** [comment]
Hopefully the service selection could be fixed, see error above:
`[ { "carrier_id": "DHL Express Test", "carrier_name": "dhl_express", "code": "DCT_0001", "message": "The requested Global Product Code L and Local Product Code L is not available between\n this origin and destination. Please make sure data entered is valid before proceeding or contact our\n customer service." } ]`

Mentioning this for [patch] 2023.4.4 #373

**Comment by danh91** [comment]
> Hopefully the service selection could be fixed, see error above:
> 
> `[ { "carrier_id": "DHL Express Test", "carrier_name": "dhl_express", "code": "DCT_0001", "message": "The requested Global Product Code L and Local Product Code L is not available between\n this origin and destination. Please make sure data entered is valid before proceeding or contact our\n customer service." } ]`
> 
> 
> 
> Mentioning this for [patch] 2023.4.4 #373 

Unfortunately, I don't think so. We need more testing with this because we spent quite some time working many scenarios to come up with the latest implementation because DHL doesn't doesn't do the filtering of valid services in advance they return everything even incompatible ones.

I don't think we will be able to get it for this patch either.

**Comment by MarcoWel** [comment]
> On another note, the example above is behaving as expected. If don't want the 10:30 premium, I think you have to choose another service.
> 
> We aren't adding it them on Karrio's side. We are just sending the shipment with the product code and since it is a dedicated 10:30 service code, DHL adds the fees for that.

But the issue is that Karrio does not offer the cheaper services at all (Standard, 12:00 etc.), only the most expensive 10:30 one. As you can see from the full response, DHL Express is sending all of them, but Karrio ignores them.

**Comment by MarcoWel** [comment]
Had another look into the full response. Here are the services offered by the DHL Express server:

```
    <LocalProductName>MEDICAL EXPRESS DOMESTIC</LocalProductName>
    <LocalProductName>EXPRESS DOMESTIC 9:00</LocalProductName>
    <LocalProductName>EXPRESS DOMESTIC 10:00</LocalProductName>
    <LocalProductName>EXPRESS DOMESTIC 12:00</LocalProductName>
    <LocalProductName>EXPRESS DOMESTIC</LocalProductName>
    <LocalProductName>EXPRESS EASY DOC</LocalProductName>
```

So karrio seems to invent services for domestic shipments, and is missing some (9:00, 12:00, and without addition).
Seems like another mapping issue?

**Comment by danh91** [comment]
> > On another note, the example above is behaving as expected. If don't want the 10:30 premium, I think you have to choose another service.
> 
> > 
> 
> > We aren't adding it them on Karrio's side. We are just sending the shipment with the product code and since it is a dedicated 10:30 service code, DHL adds the fees for that.
> 
> 
> 
> But the issue is that Karrio does not offer the cheaper services at all (Standard, 12:00 etc.), only the most expensive 10:30 one. As you can see from the full response, DHL Express is sending all of them, but Karrio ignores them.

What the filter is doing right now is removing envelope rates from the response if the packaging is a parcel (not document). The 12:00 is returned but if you are sending a parcel and not an envelope, it is invalid and the request fails or might work but is invalid because doc would be expected by DHL

**Comment by MarcoWel** [comment]
It definitely looks like a mapping issue to me.

- 12.56 EUR "EXPRESS DOMESTIC" is shown as "DHL EXPRESS" and fails (product code overridden by karrio)
- 16.52 EUR "EXPRESS DOMESTIC 12:00" is shown as "DHL EXPRESS 10 30" and fails (product code overridden by karrio)
- 25.77 EUR "EXPRESS DOMESTIC 10:00" is shown as "EXPRESS DOMESTIC 10 30"
- 38.98 EUR "EXPRESS DOMESTIC 9:00" is missing in karrio
- 19.40 EUR "DHL EXPRESS EASY" is for docs only, but still shown for "Your Packaging" with 10cm height
- 58.81 EUR "MEDICAL EXPRESS DOMESTIC" is shown as "BREAKBULK EXPRESS" by karrio

**Comment by MarcoWel** [comment]
Yep, now it is clear. Seems like the product codes are not consistent...

GlobalProductCode / LocalProductCode from the response:
```
C / B - MEDICAL EXPRESS DOMESTIC
I / H - EXPRESS DOMESTIC 9:00
O / O - EXPRESS DOMESTIC 10:00
1 / L - EXPRESS DOMESTIC 12:00
N / E - EXPRESS DOMESTIC
7 / 7 - EXPRESS EASY DOC
```

Might be better to map by "ProductShortName" or "LocalProductName" instead of ProductCode...

**Comment by MarcoWel** [comment]
Tested 2023.4.4.01 - it works for domestic shipments now.

Some minor issues remaining:

1. Service "EXPRESS EASY DOC" (GlobalProductCode "7") is suggested for domestic shipments even with "Documents Only" deselected.
2. Only "EXPRESS WORLDWIDE NONDOC" (GlobalProductCode "P") is displayed for EU shipments, other service "EXPRESS CHOICE NONDOC" (GlobalProductCode "3") is not shown. Full response attached.
3. "Preferred Shipping Services" carrier config available for UPS but not DHL Express.

[dhl_express_rate_req_response2.xml.txt](https://github.com/karrioapi/karrio/files/11547140/dhl_express_rate_req_response2.xml.txt)

**Comment by danh91** [comment]
Did you get a chance to test the latest release with this.
Should have been addressed.

Let me know.

Thanks

**Comment by danh91** [comment]
> Tested 2023.4.4.01 - it works for domestic shipments now.
> 
> Some minor issues remaining:
> 
> 1. Service "EXPRESS EASY DOC" (GlobalProductCode "7") is suggested for domestic shipments even with "Documents Only" deselected.
> 2. Only "EXPRESS WORLDWIDE NONDOC" (GlobalProductCode "P") is displayed for EU shipments, other service "EXPRESS CHOICE NONDOC" (GlobalProductCode "3") is not shown. Full response attached.
> 3. "Preferred Shipping Services" carrier config available for UPS but not DHL Express.
> 
> [dhl_express_rate_req_response2.xml.txt](https://github.com/karrioapi/karrio/files/11547140/dhl_express_rate_req_response2.xml.txt)

I went through those issues
1 - I fixed the filter on karrio's end because it was excluding both DOC and NONDOC sometimes
     -> But I added the config for DHL express and introduced `skip_service_filter` which will disable the DOC filter altogether for more control
2 - I investigated the log file and the `EXPRESS CHOICE NONDOC` was filtered out because karrio also exclude quotes that are `0.0` because though they are returned from DHL they are invalid.

3 - The release `2023.5` adds the carrier config for both FedEx and DHL Express. We will gradually add of any other missing.
