### ISSUE TITLE
DPDHL: Support for Packstation/Postfiliale, Address Field Mapping

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio#370]
**Is your feature request related to a problem? Please describe.**
DPDHL allows sending shipments to a parcel station (Packstation) or post office (Postfiliale) directly for self-pickup by the customer.
- https://www.dhl.de/en/privatkunden/pakete-empfangen/an-einem-abholort-empfangen/packstation.html
- https://www.dhl.de/en/privatkunden/pakete-empfangen/an-einem-abholort-empfangen/filiale-empfang.html

All DHL wants is the term "Packstation" or "Postfiliale" in street name, the 3-digit location number in street number, and the customer's Postnummer (8 to 12 digits) in the second address line.

**Describe the solution you'd like**
Karrio would support this already, but label creation fails due to wrong field mapping.

Karrio 2023.4.2 (field "Street No." is ditched):
```xml
  <Receiver>
    <cis:name1>Name</cis:name1>
    <Address>
       <cis:name2>Company</cis:name2>
       <cis:name3>NOT USED</cis:name3>
       <cis:streetName>Street (Line 1)</cis:streetName>
       <cis:streetNumber>Unit (Line 2)</cis:streetNumber>
       <cis:zip>Postal Code</cis:zip>
       <cis:city>City</cis:city>
       <cis:Origin>
          <cis:country>Country</cis:country>
          <cis:countryISOCode>...</cis:countryISOCode>
       </cis:Origin>
    </Address>
    <Communication>
       <cis:phone>Phone</cis:phone>
       <cis:email>Email</cis:email>
       <cis:contactPerson>NOT USED</cis:contactPerson>
    </Communication>
 </Receiver>
```

Correct:
```xml
  <Receiver>
    <cis:name1>Company (or Name if Company is empty)</cis:name1>
    <Address>
       <cis:name2>Unit (Line 2)</cis:name2>
       <cis:name3>NOT USED</cis:name3>
       <cis:streetName>Street (Line 1)</cis:streetName>
       <cis:streetNumber>Street No.</cis:streetNumber>
       <cis:zip>Postal Code</cis:zip>
       <cis:city>City</cis:city>
       <cis:Origin>
          <cis:country>Country</cis:country>
          <cis:countryISOCode>...</cis:countryISOCode>
       </cis:Origin>
    </Address>
    <Communication>
       <cis:phone>Phone</cis:phone>
       <cis:email>Email</cis:email>
       <cis:contactPerson>Name (or empty if Company is empty)</cis:contactPerson>
    </Communication>
 </Receiver>
```

**Describe alternatives you've considered**
Karrio could alternatively offer distinct address forms/fields depending on the address type. This would make it clearer for the user but quite a bit more complex to implement.

**Additional context**
See "Request DHL Paket an Packstation - Variante 2 (V01PAK)":
https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/current/operationen/createshipmentorder/beispieldaten
```xml
    <Receiver>
      <cis:name1>Empfänger Zeile 1</cis:name1>
      <Address>
         <cis:name2>12345678</cis:name2>
         <cis:name3>Empfänger Zeile 3</cis:name3>
         <cis:streetName>Packstation</cis:streetName>
         <cis:streetNumber>102</cis:streetNumber>
         <cis:zip>28195</cis:zip>
         <cis:city>Bremen</cis:city>
         <cis:Origin>
            <cis:country></cis:country>
            <cis:countryISOCode>DE</cis:countryISOCode>
         </cis:Origin>
      </Address>
      <Communication>
         <cis:phone>+49421123456789</cis:phone>
         <cis:email>empfaenger@dhl.local</cis:email>
         <cis:contactPerson>Kontaktperson Empfänger</cis:contactPerson>
      </Communication>
   </Receiver>
```

**Comment by danh91** [comment]
Hi @MarcoWel ,

Here is the data mapping on `2023.4.2` for DPDHL:

https://github.com/karrioapi/karrio/blob/5d9272b6eef71cd801aa4361c51f61268d80f57a/sdk/extensions/dpdhl/karrio/providers/dpdhl/shipment/create.py#L256-L289

If I understand correctly when using `Packstation`, `name2=recipient.address_line2`  instead of company_name

So the mapping will be something like this:

```python
...
Receiver=dpdhl.ReceiverType(
    name1=(recipient.person_name or recipient.company_name),
    Address=dpdhl.ReceiverNativeAddressType(
        name2=(
            recipient.address_line2
            if "packstation"
            in (recipient.address_line2 or "").lower()
            else recipient.company_name
        ),
 ...
```

Would that fix the issue?

**Comment by MarcoWel** [comment]
@danh91 The field mapping is generally wrong for DPDHL, not only when using Packstation/Postfiliale.
With the mapping suggested in the issue post, it will both fix the wrong mapping and make Packstation/Postfiliale usable.

Please note that if street_number is not filled in karrio, the user must provide the street_number included in the address_line1 field. In any case, Unit (Line 2) should **never** be mapped to street_number, it is not meant for that.

Here is the Python mapping code:

```python
Receiver=dpdhl.ReceiverType( 
     # Provide company_name first if it is specified!
     name1=(recipient.company_name or recipient.person_name),
     Address=dpdhl.ReceiverNativeAddressType( 
         # address_line2 always belongs in name2!
         name2=recipient.address_line2,
         name3=None, 
         # removing recipient.street_name here, streetNumber can be included within address_line1 OR be provided separately via street_number
         streetName=recipient.address_line1,
         # remove recipient.address_line2 here, it never belongs in streetNumber!
         streetNumber=recipient.street_number,
         addressAddition=None, 
         dispatchingInformation=None, 
         zip=dpdhl.ZipType(recipient.postal_code), 
         city=recipient.city, 
         province=recipient.state_code, 
         Origin=dpdhl.CountryType( 
             country=recipient.country_name, 
             countryISOCode=recipient.country_code, 
         ), 
     ),  
     Packstation=None, 
     Postfiliale=None, 
     Communication=( 
         dpdhl.CommunicationType( 
             phone=recipient.phone_number, 
             email=recipient.email, 
             # put person_name here if name1 contains company_name
             contactPerson=(recipient.person_name if recipient.company_name else ""),
         ) 
         if recipient.has_contact_info 
         else None 
     ), 
 ), 
```

**Comment by danh91** [comment]
On that note, Have you noticed any issues with the shipper address?

It currently looks like this
```python
Shipper=dpdhl.ShipperType(
    Name=dpdhl.NameType(
        *lib.join(
            shipper.person_name,
            shipper.company_name or " ",
        )
    ),
...
),
```

From the sample here:
https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/current/operationen/createshipmentorder/beispieldaten

```
             <Shipper>
                  <Name>
                     <cis:name1>Absender Zeile 1</cis:name1>
                     <cis:name2>Absender Zeile 2</cis:name2>
                     <cis:name3>Absender Zeile 3</cis:name3>
                  </Name>
                  <Address>
                     <cis:streetName>Vegesacker Heerstr.</cis:streetName>
                     <cis:streetNumber>111</cis:streetNumber>
                     <cis:zip>28757</cis:zip>
                     <cis:city>Bremen</cis:city>
                     <cis:Origin>
                        <cis:country></cis:country>
                        <cis:countryISOCode>DE</cis:countryISOCode>
                     </cis:Origin>
                  </Address>
                  <Communication>
                     <!--Optional:-->
                     <cis:phone>+49421987654321</cis:phone>
                     <cis:email>absender@dhl.local</cis:email>
                     <!--Optional:-->
                     <cis:contactPerson>Kontaktperson Absender</cis:contactPerson>
                  </Communication>
               </Shipper>
```

Considering "Absender Zeile 1" > means 😅  "Sender line 1",

Should the code be?

```python
Shipper=dpdhl.ShipperType(
    Name=dpdhl.NameType(
       name1=shipper.address_line1,
       name2=shipper.address_line2,
    ),
...
),
```

**Comment by danh91** [comment]
> @danh91 The field mapping is generally wrong for DPDHL, not only when using Packstation/Postfiliale. With the mapping suggested in the issue post, it will both fix the wrong mapping and make Packstation/Postfiliale usable.
> 
> Please note that if street_number is not filled in karrio, the user must provide the street_number included in the address_line1 field. In any case, Unit (Line 2) should **never** be mapped to street_number, it is not meant for that.
> 
> Here is the Python mapping code:
> 
> ```python
> Receiver=dpdhl.ReceiverType( 
>      # Provide company_name first if it is specified!
>      name1=(recipient.company_name or recipient.person_name),
>      Address=dpdhl.ReceiverNativeAddressType( 
>          # address_line2 always belongs in name2!
>          name2=recipient.address_line2,
>          name3=None, 
>          # removing recipient.street_name here, streetNumber can be included within address_line1 OR be provided separately via street_number
>          streetName=recipient.address_line1,
>          # remove recipient.address_line2 here, it never belongs in streetNumber!
>          streetNumber=recipient.street_number,
>          addressAddition=None, 
>          dispatchingInformation=None, 
>          zip=dpdhl.ZipType(recipient.postal_code), 
>          city=recipient.city, 
>          province=recipient.state_code, 
>          Origin=dpdhl.CountryType( 
>              country=recipient.country_name, 
>              countryISOCode=recipient.country_code, 
>          ), 
>      ),  
>      Packstation=None, 
>      Postfiliale=None, 
>      Communication=( 
>          dpdhl.CommunicationType( 
>              phone=recipient.phone_number, 
>              email=recipient.email, 
>              # put person_name here if name1 contains company_name
>              contactPerson=(recipient.person_name if recipient.company_name else ""),
>          ) 
>          if recipient.has_contact_info 
>          else None 
>      ), 
>  ), 
> ```

@MarcoWel can you highlight any "wrong" mapping while we are fixing the issues above so that we can add them to the coming patch `2023.4.4`.

Thanks

**Comment by MarcoWel** [comment]
@danh91 All affected lines are commented accordingly in my code example above.

For the sender, I would map it identically to the receiver (with the new fixed mapping).

**Comment by MarcoWel** [comment]
All above based on the assumption that:

- address_line1 = "Street (Line 1)" in karrio Dashboard
- address_line1 = "Unit (Line 2)" in karrio Dashboard

**Comment by danh91** [comment]
> @danh91 All affected lines are commented accordingly in my code example above.
> 
> For the sender, I would map it identically to the receiver (with the new fixed mapping).

The sender is actually different if you look at the sample requests here.
The schema is different https://entwickler.dhl.de/group/ep/wsapis/geschaeftskundenversand/current/operationen/createshipmentorder/beispieldaten

**Comment by MarcoWel** [comment]
Yes, but only slightly. Here you go:

```python
Shipper=dpdhl.ShipperType(
    Name=dpdhl.NameType(
       # Provide company_name first if it is specified!
       name1=(shipper.company_name or shipper.person_name),
       # address_line2 always belongs in name2!
       name2=shipper.address_line2,
    ),
    Address=dpdhl.NativeAddressTypeNew(
        # not sure if address_line1 alone would be sufficient here?
        streetName=(
            shipper.street_name or shipper.address_line1
        ),
        # remove address_line2 here, it never belongs in streetNumber!
        streetNumber=sender.street_number,
        addressAddition=None,
        dispatchingInformation=None,
        zip=dpdhl.ZipType(shipper.postal_code),
        city=shipper.city,
        province=shipper.state_code,
        Origin=dpdhl.CountryType(
            country=shipper.country_name,
            countryISOCode=shipper.country_code,
        ),
    ),
    Communication=(
        dpdhl.CommunicationType(
            phone=shipper.phone_number,
            email=shipper.email,
            # put person_name here if name1 contains company_name
            contactPerson=(shipper.person_name if shipper.company_name else ""),
        )
        if shipper.has_contact_info
        else None
    ),
),
```
