### ISSUE TITLE
File Wont Open Anymore

### ISSUE THREAD

**Issue by AlmightyStrikeLord** [karrioapi/karrio#398]
The file wouldn't load anymore & when I went into to see what's wrong .

[{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingModuleSource"
		}
	},
	"severity": 4,
	"message": "Import \"tqdm\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 6,
	"endLineNumber": 3,
	"endColumn": 10
},{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingModuleSource"
		}
	},
	"severity": 4,
	"message": "Import \"colorama\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 6,
	"endLineNumber": 4,
	"endColumn": 14
},{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingModuleSource"
		}
	},
	"severity": 4,
	"message": "Import \"requests\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 8,
	"endLineNumber": 5,
	"endColumn": 16
},{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"user_agent\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 6,
	"endLineNumber": 6,
	"endColumn": 16
},{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"pyfiglet\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 6,
	"endLineNumber": 8,
	"endColumn": 14
},{
	"resource": "/c:/Users/nicol/Downloads/V1/V1/carrier_v.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingModuleSource"
		}
	},
	"severity": 4,
	"message": "Import \"bs4\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 9,
	"startColumn": 6,
	"endLineNumber": 9,
	"endColumn": 9
}]

This Pops Up

**Comment by danh91** [comment]
Hi @AlmightyStrikeLord, 

Could you please follow the issue template to better explain the problem?

I don't understand the issue above. How to reproduce it?

Thanks
