### ISSUE TITLE
[carrier-integration] Upgrade outdated DPDHL integration

### ISSUE THREAD

**Issue by bxschmidt** [karrioapi/karrio#417]
Hi all,
the current dpdhl integration links to an api provided by https://entwickler.dhl.de/
The documentation for the api the karrio calls are directed to states that new users are no longer accepted and redirects users to
https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2#get-started-section/
which uses json instead of xml and has a different endpoint.
It is still possible to get access to the legacy api by contacting support but the current karrio implementation is not a long term solution.
Great project!

Best regards
Sebastian

**Comment by danh91** [comment]
Hi @bxschmidt ,
Thanks for opening the issue. You are correct we need to migrate to the new API for DPDHL.
I will add this issue to the roadmap to keep track of it with the other upgrades in progress (FedEx, DHL Express...)

**Comment by MarcoWel** [comment]
Is there a timeline for this update yet?
Here is a short overview.

## New REST API

Reading the [DHL API docs](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2?lang=en#operations-Shipments_and_Labels-createOrders), this is how a `CreateShipmentOrderRequest` should look like with the new API.

Some things to note:

- There is a Postman test collection available [here](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2?lang=en#downloads-section).
- XML authentication header of the old API is replaced by a BASIC AUTH on the POST request [explained in the docs here](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2?lang=en#get-started-section/user-guide--authentication).
- `country` code is now 3-letter according to ISO 3166-1 alpha-3. Details like this are shown in the docs when clicking "Show Data Schema" in the "Request body" section.
![image](https://github.com/karrioapi/karrio/assets/80592577/2484d448-fca4-41e0-8164-fdd6c38c8345)
- `billingNumber` still includes the DHL product in the last digits as per #333.



`POST https://api-eu.dhl.com/parcel/de/shipping/v2/orders`
```json
{
  "profile": "STANDARD_GRUPPENPROFIL",
  "shipments": [
    {
      "product": "V01PAK",
      "billingNumber": "22222222220102",
      "refNo": "",
      "shipper": {
        "name1": "Deut",
        "addressStreet": "Römerberg 23",
        "additionalAddressInformation1": "",
        "postalCode": "60311",
        "city": "Frankfurt",
        "country": "DEU",
        "email": "",
        "phone": ""
      },
      "consignee": {
        "name1": "Ana",
        "addressStreet": "Am Wall 207",
        "additionalAddressInformation1": "",
        "postalCode": "28195",
        "city": "Bremen",
        "country": "DEU",
        "email": "",
        "phone": ""
      },
      "details": {
        "dim": {
          "uom": "cm",
          "height": 18,
          "length": 10,
          "width": 33
        },
        "weight": {
          "uom": "kg",
          "value": 1
        }
      }
    }
  ]
}
```

## Old SOAP API

This was a `CreateShipmentOrderRequest` to the old API (taken from [here](https://github.com/karrioapi/karrio/issues/314#issuecomment-1471950425)):

`POST https://cig.dhl.de/services/production/soap`
```xml
<soapenv:Envelope
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:cis="http://dhl.de/webservice/cisbase"
	xmlns:ns="http://dhl.de/webservices/businesscustomershipping/3.0">
	<soapenv:Header>
		<cis:Authentification>
			<cis:user>2222222222_01</cis:user>
			<cis:signature>pass</cis:signature>
		</cis:Authentification>
	</soapenv:Header>
	<soapenv:Body>
		<ns:CreateShipmentOrderRequest>
			<ns:Version>
				<majorRelease>3</majorRelease>
				<minorRelease>4</minorRelease>
			</ns:Version>
			<ShipmentOrder>
				<sequenceNumber>1</sequenceNumber>
				<Shipment>
					<ShipmentDetails>
						<product>V01PAK</product>
						<cis:accountNumber>22222222220102</cis:accountNumber>
                                                <ShipmentItem>
							<weightInKG>1</weightInKG>
							<lengthInCM>10</lengthInCM>
							<widthInCM>33</widthInCM>
							<heightInCM>18</heightInCM>
						</ShipmentItem>
						<Notification/>
					</ShipmentDetails>
					<Shipper>
						<Name>
							<cis:name1>Deut</cis:name1>
							<cis:name2></cis:name2>
						</Name>
						<Address>
							<cis:streetName>Römerberg</cis:streetName>
							<cis:streetNumber>23</cis:streetNumber>
							<cis:zip>60311</cis:zip>
							<cis:city>Frankfurt</cis:city>
							<cis:Origin>
								<cis:country>Germany</cis:country>
								<cis:countryISOCode>DE</cis:countryISOCode>
							</cis:Origin>
						</Address>
						<Communication>
							<cis:contactPerson>Deut</cis:contactPerson>
						</Communication>
					</Shipper>
					<ShipperReference></ShipperReference>
					<Receiver>
						<cis:name1>Ana</cis:name1>
						<Address>
							<cis:streetName>Am Wall</cis:streetName>
							<cis:streetNumber>207</cis:streetNumber>
							<cis:zip>28195</cis:zip>
							<cis:city>Bremen</cis:city>
							<cis:Origin>
								<cis:country>Germany</cis:country>
								<cis:countryISOCode>DE</cis:countryISOCode>
							</cis:Origin>
						</Address>
						<Communication>
							<cis:contactPerson>Ana</cis:contactPerson>
						</Communication>
					</Receiver>
				</Shipment>
			</ShipmentOrder>
			<labelResponseType>B64</labelResponseType>
			<combinedPrinting>0</combinedPrinting>
		</ns:CreateShipmentOrderRequest>
	</soapenv:Body>
</soapenv:Envelope>
```

**Comment by MarcoWel** [comment]
## How to test DHL REST API in Postman

### Create App in DHL Developer Portal

For API testing, it is required to register on the DHL Developer Portal and request sandbox credentials by clicking on the "Get Access" button on the [API page](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2?lang=en):
![image](https://github.com/karrioapi/karrio/assets/80592577/feec94e3-91be-4169-b290-9f5ef927a804)

We need the following APIs for "Customer (Integration) Testing":
- Parcel DE Shipping (Post & Parcel Germany)
- Parcel DE Tracking (Post & Parcel Germany)

![image](https://github.com/karrioapi/karrio/assets/80592577/b222d778-3c27-448d-b8af-b8b8c50d5727)


Now the app should appear as "approved" in the Developer Portal straight away. Click "Show key" to get the required API key for testing in Postman:

![image](https://github.com/karrioapi/karrio/assets/80592577/85440492-4293-4645-b77f-4a786b4dcec2)


### Run Postman Collection

Download the [DHL Postman Collection](https://developer.dhl.com/api-reference/parcel-de-shipping-post-parcel-germany-v2?lang=en#downloads-section), import it into Postman, enter the Sandbox API key to the variables and press save. 

![image](https://github.com/karrioapi/karrio/assets/80592577/b84a488b-c488-446d-9b9e-cd5331ee1a2e)


Now you can run any of the collection requests successfully straight away.

![image](https://github.com/karrioapi/karrio/assets/80592577/2a9516c8-5ef2-4c3f-87a0-5c4efbd11dfe)


This is **much** better documented and much better to use than the old SOAP API.

**Comment by danh91** [comment]
@MarcoWel,

Thanks for the details. I am hoping to close these final tasks for the official release of `2024.2` in the second week of February.

<img width="1428" alt="Screenshot 2024-01-24 at 10 10 24 AM" src="https://github.com/karrioapi/karrio/assets/10974180/0d5dd3b7-8cb6-4a7d-9724-23a67d836d19">

https://github.com/orgs/karrioapi/projects/12/views/1
