### ISSUE TITLE
Upgrade failed (2023.9.2)

### ISSUE THREAD

**Issue by DarkSwoop** [karrioapi/karrio#452]
**Describe the bug**
When trying to update karrio via docker, the api and worker containers do not start.

I used the upgrade script and it ran without errors. The only change I subsequently made to the docker-compose.yml was to set the postgres version to 15, as I didn't want to upgrade the database to 16. Even after a complete `docker compose up -d --force-recreate` the server component (api + worker) does not come up. Log is attached below.

**Additional context**

[container.log](https://github.com/karrioapi/karrio/files/13632820/container.log)

<img width="2160" alt="running-containers" src="https://github.com/karrioapi/karrio/assets/5122/8b00fca5-4c23-492e-aa1b-6e3919ba28b7">

**Comment by danh91** [comment]
Ouch that's not good. Can you safely rollback to the previous version?
Also, is there any chance you can capture the content of `docker logs` on the server or worker images?

Thanks

**Comment by DarkSwoop** [comment]
Hi @danh91 ,

I attached the output of `docker logs`: 
[container.log](https://github.com/karrioapi/karrio/files/13632820/container.log)

**Comment by DarkSwoop** [comment]
Works great! Thank you!
