### ISSUE TITLE
DHL Express: registration numbers missing

### ISSUE THREAD

**Issue by DarkSwoop** [karrioapi/karrio#496]
**Describe the bug**
When I enter data into the customs identifications section, they are not transmitted to DHL.

**To Reproduce**
1. Create a shipment
2. open the "edit customs" dialog
3. enter data into the customs identification section
4. buy a label
5. look at the shipment request log

**Screenshots**

<img width="693" alt="customs-identifications" src="https://github.com/karrioapi/karrio/assets/5122/33287f79-f5a6-4507-87ab-70b3944e99f3">

**Comment by DarkSwoop** [comment]
That sounds excellent. Do you already have an idea when the release for this will come? And another question: Are the customs identification information stored somewhere so that one doesn't have to enter them with every new shipment?

**Comment by danh91** [comment]
Hi @DarkSwoop,

I released the patch with your PR as part of 2023.9.13. I am hoping to have https://github.com/karrioapi/karrio/pull/489 merged and released by late Saturday this week. 

You are right about the customs identification information. We used to have customs templates similar to addresses and parcels but retired them as it was a bit clunky. I am thinking of adding a user preference where things like that could be stored and automatically prefilled during shipments. It will also have things like (default measurement types, and label types ...)
What do you think?

Thank you so much for sponsoring the project. It means a lot. 
A couple of things I want to ask:
- Would you please email me at dan@karrio.io with a few bullet points of things you hope to see added to the project in terms of direction and features that would be helpful for you and your customers? 
- I would like to feature you or your company logo in the README as sponsor. 

Cheers

**Comment by DarkSwoop** [comment]
> Hi @DarkSwoop,
> 
> I released the patch with your PR as part of 2023.9.13. I am hoping to have #489 merged and released by late Saturday this week.
> 
> You are right about the customs identification information. We used to have customs templates similar to addresses and parcels but retired them as it was a bit clunky. I am thinking of adding a user preference where things like that could be stored and automatically prefilled during shipments. It will also have things like (default measurement types, and label types ...) What do you think?
> 
> Thank you so much for sponsoring the project. It means a lot. A couple of things I want to ask:
> 
>     * Would you please email me at [dan@karrio.io](mailto:dan@karrio.io) with a few bullet points of things you hope to see added to the project in terms of direction and features that would be helpful for you and your customers?
> 
>     * I would like to feature you or your company logo in the README as sponsor.
> 
> 
> Cheers

Hi @danh91 ,
Did you receive my email?

**Comment by danh91** [comment]
Hi @DarkSwoop, 
I have received your email. Thanks for taking the time. I am wrapping up the 2024.2 official release early next week.
I should have the DHL customs config sorted out with auto fill so that users don't have to add them over and over again.
