### ISSUE TITLE
[carrier-integration] Expose tracking proof of delivery for supported carriers

### ISSUE THREAD

**Issue by danh91** [karrioapi/karrio#499]

**Comment by MarcoWel** [comment]
This feature definitely deserves the #epic hashtag!

**Comment by MarcoWel** [comment]
Here is the relevant information for DHL:

- [DHL Unified Tracking API](https://developer.dhl.com/api-reference/shipment-tracking?language_content_entity=en#operations-default-getTrackingShipment) exposes the POD in the tracking response data in `shipment.details.proofOfDelivery`
- [DHL Express MyDHL API](https://developer.dhl.com/api-reference/dhl-express-mydhl-api?language_content_entity=en#operations-shipment-exp-api-shipments-epod) exposes the POD via `/shipments/{shipmentTrackingNumber}/proof-of-delivery` endpoint
- [DHL Paket DE Versenden API](https://developer.dhl.com/api-reference/dhl-parcel-de-shipment-tracking-post-parcel-germany?lang=en#operations-tag-default) has a `d-get-signature` function that has to be used in connection with the recipient zip code.

**Comment by danh91** [comment]
> Here is the relevant information for DHL:
> 
> 
> 
> - [DHL Unified Tracking API](https://developer.dhl.com/api-reference/shipment-tracking?language_content_entity=en#operations-default-getTrackingShipment) exposes the POD in the tracking response data in `shipment.details.proofOfDelivery`
> 
> - [DHL Express MyDHL API](https://developer.dhl.com/api-reference/dhl-express-mydhl-api?language_content_entity=en#operations-shipment-exp-api-shipments-epod) exposes the POD via `/shipments/{shipmentTrackingNumber}/proof-of-delivery` endpoint
> 
> - [DHL Paket DE Versenden API](https://developer.dhl.com/api-reference/dhl-parcel-de-shipment-tracking-post-parcel-germany?lang=en#operations-tag-default) has a `d-get-signature` function that has to be used in connection with the recipient zip code.

Thanks much @MarcoWel, this is amazing 🤩 I won't have to dig out these ones 😅
