### ISSUE TITLE
Fedex Customs clearance detail cannot be null.

### ISSUE THREAD

**Issue by fi0** [karrioapi/karrio#549]
1. Go to Create Label
2. Fill out Recipient, Shipper, package and Customs Info
3. Press Refresh Rates

**Expected behavior**
CUSTOM CLEARANCE DETAIL should be sent to the Fedex API

**Additional context**
```
Carrier: fedex
Connection: fedex
URL: https://apis.fedex.com/rate/v1/rates/quotes



{
  "transactionId": "...",
  "errors": [
    {
      "code": "RATE.CUSTOMCLEARANCEDETAIL.INVALID",
      "message": "Customs clearance detail cannot be null."
    }
  ]
}
```

**Comment by danh91** [comment]
Hi @fi0,

I imagine this is happening with production keys right?
🤔 that would mean that the FedEx REST API somehow require customs clearance details even for rates request

**Comment by fi0** [comment]
Yes this happened with the production keys. For rate requests, it seems to require customs clearance details for international shipments.
