### ISSUE TITLE
Preferred currency for fedex

### ISSUE THREAD

**Issue by fi0** [karrioapi/karrio#559]
![Screenshot 2024-04-10 at 16 37 10](https://github.com/karrioapi/karrio/assets/25412990/860abb71-bc11-46fe-a422-ad5ea77cf952)

Due to the multiple currencies, the sorting of price is not correct.
Is there a way to set a preferred currency for fedex please?

**Comment by danh91** [comment]
Hi @fi0,
If you can please share the logs from the `Developers > Logs` `API Request` and `Timeline`.
It helps debug faster.

If you are providing a currency under **options**, you are doing the right thing.
![currency](https://github.com/karrioapi/karrio/assets/10974180/c957030b-7be1-4ad2-a0b6-e8d9448b7b0a)

I am investigating the rates parsing to see if it prioritized preferred currency rates correctly
