### ISSUE TITLE
redis connection refused 

### ISSUE THREAD

**Issue by zainali99** [karrioapi/karrio#586]
hi
when i start the server with docker compose the redis is starting but then from worker is saying connection refused,
someone know the solution ?
![image](https://github.com/karrioapi/karrio/assets/9899154/6920b1ec-1a68-4292-8e04-7950f114d47c)

when i start the server is like this the logs:
![image](https://github.com/karrioapi/karrio/assets/9899154/591c2fdc-c256-40f2-bee6-797f82f66775)

**Comment by danh91** [comment]
Hi @zainali99 
Can you confirm that only the dashboard goes down and not the server?

If so. Is there anything running on port 3000?

Did you make any configuration changes for redis? 

Last, can you confirm that the redis server doesn't require a password.

Thanks

**Comment by danh91** [comment]
Actually forget these questions. I see that there is a warning on the redis container logs.
Can you please that the redis server doesn't die?

**Comment by zainali99** [comment]
Hi, the redis server die or it is something that affects this situation in docker mode,
instead, i follow these lines and this is working with python venv
https://docs.karrio.io/product/resources/development#installation

**Comment by danh91** [comment]
Alright, I am going to pull the latest image with a fresh install on my end to test it.
I suspect the latest Redis image might have some configuration issues.

**Comment by danh91** [comment]
Hi @zainali99 , 
The instructions on https://docs.karrio.io/product/resources/development#installation are perfect for development and testing Karrio locally. The docker deployment is more suited for production.

I tried pulling the latest image and couldn't reproduce the issue. 

If you want to use the docker image, I recommend debugging the Redis container. For some reason, it seems to have an issue with your VM. 
Check the logs line with `sysctl vm.overcommit_memory=1...`
