### ISSUE TITLE
Preferences for specific services of a carrier

### ISSUE THREAD

**Issue by DarkSwoop** [karrioapi/karrio#608]
So far, we insure all packages that we send. In Karrio, we have to regularly click the checkbox and enter the corresponding value for this. We wonder if there isn't some kind of preference or similar that makes such things happen automatically.

**Comment by danh91** [comment]
Hi @DarkSwoop,
Correct me if I am wrong, but the insurance option takes a coverage amount as input. 
What would you see as a default value for that? Should it be the full package declared value?

We can definitely add something to the workspace preference to autofill/pre-check the box. 🤔

**Comment by DarkSwoop** [comment]
> Correct me if I am wrong, but the insurance option takes a coverage amount as input.
What would you see as a default value for that? Should it be the full package declared value?

For our use case, the total package declared value would be fantastic.

**Comment by DarkSwoop** [comment]
@ danh91 Do you have any updates on this?
