### ISSUE TITLE
API request log size growing quite large

### ISSUE THREAD

**Issue by mazzarito** [karrioapi/karrio#609]
Is there a way to limit the size of these tables? They've grown to over 30GB in the past week or so ... Is it safe to just truncate the rest_framework_tracking_apirequestlog and/or tracing-record tables or is there a better way to do this?

Thanks!

**Comment by danh91** [comment]
Hi @mazzarito,
Out of curiosity, 
- Would you be comfortable sharing about your transaction volume? In let's say a week? (how many labels generated etc...)
- Are you familiar with the https://[YOUR-KARRIO-API]/admin/constance/config/? 
Under the `Data retention` section, it is possible to reduce the data retention for API logs and tracing record `API_LOGS_DATA_RETENTION`

**Comment by mazzarito** [comment]
Ah great, not sure how I missed that.

It's quite high, I'll have to check on the exact volume but quite a lot of time in transit type requests, not so many labels but maybe 20 a day. Probably thousands of time in transit/rate requests... 

I noticed that in the admin menu it's impossible to save those settings, is that just not complete yet? Guessing I have to edit the env file to make those changes stick at the moment?

**Comment by danh91** [comment]
The environment variable sets the default but once you set a value from the constance/config page and save, it take precedence over the environment variable value.

There is one save button all the way at the button for all the Constance values.

I would be curious if you see any changes or improvements with let's say 30 days log retention.
