### ISSUE TITLE
Add colissimo carrier

### ISSUE THREAD

**Issue by KaraSery** [karrioapi/karrio#628]
**Describe the bug**
Hi ! I' try to test karrio basic local developpement. I'm trying to add colissimo carrier but i can't set the contract_number, i tried with api_key and password but it doesn't work. 
**To Reproduce**
1. Go to 'Carriers'
2. Click on 'Register carrier'
3. Select 'colissimo'

i got this error in my terminal Variable '$data' got invalid value {'carrier_id': 'colissimo', 'laposte_api_key': 'api_key', 'password': 'password'} at 'data.colissimo'; Field 'contract_number' of required type 'String!' was not provided.

**Comment by danh91** [comment]
Hi @KaraSery,
It looks like the `contract_number` field is missing from the form. 
I will add a fix to the upcoming patch.

**Comment by KaraSery** [comment]
Ok thanks ! 
I managed to add colissimo carrier using the graphql api, but now when i try to refresh rates in the create label form i got this error : 'colissimo 'Settings' object has no attribute 'shipping_services''. Should i add services manually ? i didn't find the doc for adding services. 
Thank youagain for your work !
