### ISSUE TITLE
Unable to get colissimo shipping rates

### ISSUE THREAD

**Issue by KaraSery** [karrioapi/karrio#630]
**Describe the bug**
Hi! 
I'm trying to get shipping rates from dashboard, i connected colissimo carrier.
I fullfilled recipient and shipper forms but i got this error : "colissimo 'Settings' object has no attribute 'shipping_services'"

**To Reproduce**
1. Add colissimo carrier with correct contract number and password
1. Go to 'http://localhost:3000/create_label?shipment_id=new'
2. Fulfill recipient and shipper froms 
3. Click on 'Refresh rates.

**Comment by danh91** [comment]
This was fixed with the 2024.6-rc24 release
