### ISSUE TITLE
Exporter declaration for DHL shipment API calls

### ISSUE THREAD

**Issue by DarkSwoop** [karrioapi/karrio#631]
There were problems with the customs declaration on DHL's side. DHL takes responsibility for this because they entered incorrect data on their end.

However, DHL is asking us to include the exporter declaration in the API request. I've checked the code and seen that the exporter declaration is currently simply set to `None`. Can we somehow manage to transmit the exporter to DHL via API?

**Comment by danh91** [comment]
Definitely. I will look into it to see what needs to be collected.

**Comment by DarkSwoop** [comment]
Great! Thanks!
