### ISSUE TITLE
add-tracker API call isn't finding existing tracker and adding a duplicate

### ISSUE THREAD

**Issue by ChrisNolan** [karrioapi/karrio#660]
**Describe the bug**
Using the ['add-tracker'](https://docs.karrio.io/reference/api/add-tracker/) API call for the same tracking_number a 2nd time adds a 2nd tracker, where the documentation says " ..or retrieves (if existent).. ".

**To Reproduce**

Call the API once.  Call it again.

**Expected behavior**
I had expected it to use the existing tracker, and re-call out to the carrier to get 'updated' information for that tracker and return that updated info.

**Screenshots**
![image](https://github.com/user-attachments/assets/a9dc5062-88dd-4ade-8576-254c7613148c)

**Desktop (please complete the following information):**
N/A

**Additional context**

If you can point me in the 'right direction' I can look into trying to track down and solve this myself if you'd like.

**Comment by danh91** [comment]
Hi @ChrisNolan ,
Thanks for the clean issue report.

I addressed it in the `rc33` release. When you get a chance please test it on your end as well.

We will reopen this if you encounter any issue

**Comment by ChrisNolan** [comment]
That did fix it for the API call... I think there might still be an issue with using the "Track A Shipment" button on the dashboard itself though...
![image](https://github.com/user-attachments/assets/3f006721-9912-4ade-8ff9-fedf7ab2f637)
(and look at that 'signed by' on the Dashboard... snazzy eh? ... coming soon to a pull request near you).
