### ISSUE TITLE
UPS integration - reference number on packages/labels?

### ISSUE THREAD

**Issue by mazzarito** [karrioapi/karrio#667]
**Is your feature request related to a problem? Please describe.**

This might be a bug or might be an oversight, basically for UPS packages they provide the ability to set a reference number, which shows up on each package label and in their billing portal (easy way to connect shipments to orders if you're doing ecommerce related shipments). Currently, I've set the reference number in my create label request for both the overall shipment and for the individual packages, and neither is showing up on the label. I noticed the field is missing from the resulting UPS request in the logs.

**Describe the solution you'd like**

Basically, in `main/modules/connectors/ups/karrio/providers/ups/shipment/create.py` can we set the ReferenceNumber to something we pass in the API properly? I don't think we need any new API params, necessarily just need to support this field from the docs:

https://developer.ups.com/api/reference?loc=en_US#operation/Shipment!path=ShipmentRequest/Shipment/Package/ReferenceNumber&t=request

![image](https://github.com/user-attachments/assets/ea7b5147-cd8b-4fcc-bb28-2baefa341516)

Its a bit confusing but, I think this is the field that shows up on the label, looking at my pre-oauth integration code we used in the past.

Thanks for the great tool, and for fixing the issue with the return_address I raised previously! I wish I knew python a bit better and I'd submit a PR myself but you'd probably just end up re-doing it anyway =)

**Comment by danh91** [comment]
Hey @mazzarito ,

Thanks for the detailed report. We definitely want to have at least the shipment reference passed down on the label.
It's indeed just a matter of adding mapping the data to pass the `package.reference_number`

**Comment by mazzarito** [comment]
@danh91 I'm gonna submit a PR, might inform how to proceed but... I also noticed that the current implementation of the `ReferenceNumber.code` for UPS seems a bit off - this is an optional field, so maybe best to leave it out anyway but, these are the valid codes below.

It seems like the country code is being populated here instead unless I'm missing something. The docs do say that you can only use this field if the destination is US/PR but doesn't indicate this field should be filled by the country code AFAIK.

Valid codes:

![image](https://github.com/user-attachments/assets/ea94a311-088c-423a-92d6-a8dce287eb75)

Current implementation, notice shipper.country_code:

```python
                ReferenceNumber=(
                    ups.ReferenceNumberType(
                        BarCodeIndicator=None,
                        Code=shipper.country_code,
                        Value=payload.reference,
                    )
                    if (country_pair not in ["US/US", "PR/PR"])
                    and any(payload.reference or "")
                    else None
                ),
```

Maybe instead, just remove the two optional fields:

```python
                ReferenceNumber=(
                    ups.ReferenceNumberType(
                        Value=payload.reference,
                    )
                    if (country_pair not in ["US/US", "PR/PR"])
                    and any(payload.reference or "")
                    else None
                ),
```

And since package reference_number is already a thing, this should work I think? ReferenceNumberType already all optional fields, but haven't tested yet.


```python
[...]
                        UPSPremier=None,
                        ReferenceNumber=(
                            ups.ReferenceNumberType(
                                Value=package.reference_number,
                            )
                            if (country_pair not in ["US/US", "PR/PR"])
                               and any(package.reference_number or "")
                            else None
                        ),
                    )
                    for package in packages
                ],
            ),
```

**Comment by danh91** [comment]
> @danh91 I'm gonna submit a PR, might inform how to proceed but... I also noticed that the current implementation of the `ReferenceNumber.code` for UPS seems a bit off - this is an optional field, so maybe best to leave it out anyway but, these are the valid codes below.
> 
> It seems like the country code is being populated here instead unless I'm missing something. The docs do say that you can only use this field if the destination is US/PR but doesn't indicate this field should be filled by the country code AFAIK.
> 
> Valid codes:
> 
> ![image](https://private-user-images.githubusercontent.com/1696887/364071124-ea94a311-088c-423a-92d6-a8dce287eb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzODM5ODcsIm5iZiI6MTcyNTM4MzY4NywicGF0aCI6Ii8xNjk2ODg3LzM2NDA3MTEyNC1lYTk0YTMxMS0wODhjLTQyM2EtOTJkNi1hOGRjZTI4N2ViNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMTcxNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRmNjI1YmYxYWQwNDc5MmI5Y2MxYzNiM2Q4N2RhMzA3YzNiYjRlNjRmZjE1ZWM3NzNjMzgwZTgyNzIyNTM1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b5BygQgCr-pXjlIz6Me0LXk9roFRpbdfRLOB7jN4wi8)
> 
> Current implementation, notice shipper.country_code:
> 
> ```python
>                 ReferenceNumber=(
>                     ups.ReferenceNumberType(
>                         BarCodeIndicator=None,
>                         Code=shipper.country_code,
>                         Value=payload.reference,
>                     )
>                     if (country_pair not in ["US/US", "PR/PR"])
>                     and any(payload.reference or "")
>                     else None
>                 ),
> ```
> 
> Maybe instead, just remove the two optional fields:
> 
> ```python
>                 ReferenceNumber=(
>                     ups.ReferenceNumberType(
>                         Value=payload.reference,
>                     )
>                     if (country_pair not in ["US/US", "PR/PR"])
>                     and any(payload.reference or "")
>                     else None
>                 ),
> ```
> 
> And since package reference_number is already a thing, this should work I think? ReferenceNumberType already all optional fields, but haven't tested yet.
> 
> ```python
> [...]
>                         UPSPremier=None,
>                         ReferenceNumber=(
>                             ups.ReferenceNumberType(
>                                 Value=package.reference_number,
>                             )
>                             if (country_pair not in ["US/US", "PR/PR"])
>                                and any(package.reference_number or "")
>                             else None
>                         ),
>                     )
>                     for package in packages
>                 ],
>             ),
> ```

Yup, you are correct about that. And yes the `package.reference_number` is perfect for this package-specific reference.
Please go ahead with the PR. I will test and make any adjustment necessary before merging
