### ISSUE TITLE
Next.js cache not cleared on upgrade?

### ISSUE THREAD

**Issue by ChrisNolan** [karrioapi/karrio#688]
**Describe the bug**

The first start up after an upgrade results in errors from the ".next" "chunks".

I suspect this is because the 'cached'/'generated' page still exists in the .next folder, but the code itself has changed and some of the dynamic pieces is trying to use an old 'chunk'.  I think likely there just has to be a process to remove the '.next' folder when doing an upgrade from one version to the next perhaps?

---
Got this error repeated in the logs until I first logged in

```
karrio.dashboard  | [auth][error] UnknownAction: Cannot parse action at /api/auth/_log. Read more at https://errors.authjs.dev#unknownaction
karrio.dashboard  |     at /app/.next/server/chunks/8481.js:1:79564
karrio.dashboard  |     at nr (/app/.next/server/chunks/8481.js:1:79734)
karrio.dashboard  |     at ca (/app/.next/server/chunks/8481.js:1:178046)
karrio.dashboard  |     at t (/app/.next/server/chunks/8481.js:1:188408)
karrio.dashboard  |     at /app/.next/server/app/api/auth/[...nextauth]/route.js:1:4071
karrio.dashboard  |     at s (/app/.next/server/chunks/4084.js:1:32311)
karrio.dashboard  |     at /app/.next/server/app/api/auth/[...nextauth]/route.js:1:4063
karrio.dashboard  |     at status (/app/.next/server/chunks/4084.js:1:29071)
karrio.dashboard  |     at s (/app/.next/server/chunks/4084.js:1:32311)
karrio.dashboard  |     at /app/.next/server/chunks/4084.js:1:29065
```

I believe it is probably just 'stale' generated nextjs stuff?  Could there be a step in the migration to clear the nextjs cache (i.e. rm .next) so it will rebuild on first hit -- or, do we want to force the build of the nextjs system whenever a new image is spun up?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ChrisNolan** [comment]
Oh, and I think this is likely also I had a tab open that was redirected to the login page as well and perhaps there is some script in the auth.js stuff which is trying to do the refreshes or something?

**Comment by danh91** [comment]
Hi @ChrisNolan ,
I am investigating this. I suspect the issue might also come from the switch from Nextjs `page router` to  `app router`.
