### ISSUE TITLE
UPS Shipment Not working. RatedShipmentType/TotalCharge Error

### ISSUE THREAD

**Issue by welpak** [karrioapi/karrio#703]
**Describe the bug**
Using Karrio 2024.9.4, I am not able to create a ups shipment. When I send it, everything goes through but I get this error: 

424 - 
Your request is invalid or could not be processed by the service
'RatedShipmentType' object has no attribute 'TotalCharge'

424 - "{\"messages\":[{\"carrier_id\":\"ups\",\"carrier_name\":\"ups\",\"code\":\"SHIPPING_SDK_INTERNAL_ERROR\",\"message\":\"'RatedShipmentType' object has no attribute 'TotalCharge'\"}]}"

**To Reproduce**
1. Use the Karrio API
2. Send Create Shipment POST

**Expected behavior**
To create the shipment.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser Brave/Chrome
 - Version [1.70.119]

Full Request:
{
  "RateRequest": {
    "Request": {
      "RequestOption": "Shoptimeintransit",
      "SubVersion": "2205",
      "TransactionReference": {
        "CustomerContext": "Order #12345"
      }
    },
    "Shipment": {
      "DeliveryTimeInformation": {
        "PackageBillType": "03",
        "Pickup": {
          "Date": "20241004"
        }
      },
      "InvoiceLineTotal": {
        "CurrencyCode": "USD",
        "MonetaryValue": "1.0"
      },
      "Package": [
        {
          "Dimensions": {
            "Height": "5.0",
            "Length": "4.0",
            "UnitOfMeasurement": {
              "Code": "IN",
              "Description": "Dimension"
            },
            "Width": "10.0"
          },
          "PackageWeight": {
            "UnitOfMeasurement": {
              "Code": "LBS",
              "Description": "Weight"
            },
            "Weight": "2.0"
          },
          "PackagingType": {
            "Code": "02",
            "Description": "Packaging Type"
          }
        }
      ],
      "PaymentDetails": {
        "ShipmentCharge": {
          "BillShipper": {
            "AccountNumber": "<OUR ACCOUNT #>"
          },
          "Type": "01"
        }
      },
      "RatingMethodRequestedIndicator": "Y",
      "Service": {
        "Code": "11",
        "Description": "Weight"
      },
      "ShipFrom": {
        "Address": {
          "AddressLine": "101 Industrial Dr.",
          "City": "Louisburg",
          "CountryCode": "US",
          "PostalCode": "27549",
          "StateProvinceCode": "NC"
        },
        "AttentionName": "Welpak"
      },
      "ShipTo": {
        "Address": {
          "AddressLine": "35 Walnut St",
          "City": "Spotswood",
          "CountryCode": "US",
          "PostalCode": "08884-2158",
          "ResidentialAddressIndicator": "Y",
          "StateProvinceCode": "NJ"
        },
        "AttentionName": "Wayne Narkiewicz"
      },
      "ShipmentRatingOptions": {
        "NegotiatedRatesIndicator": "Y"
      },
      "ShipmentTotalWeight": {
        "UnitOfMeasurement": {
          "Code": "LBS",
          "Description": "Dimension"
        },
        "Weight": "2.0"
      },"

![image](https://github.com/user-attachments/assets/83043fdd-8ef9-41c4-87c5-83e31cdaeb5f)

**Comment by danh91** [comment]
Thanks @welpak for reporting this. 
It looks like the UPS rate parsing regression isn't fully solved.
