### ISSUE TITLE
Incorrect value used for 'VERSION' during build?

### ISSUE THREAD

**Issue by ChrisNolan** [karrioapi/karrio#730]
It feels like this line of code is 'wrong', it was introduced in [this commit](https://github.com/karrioapi/karrio/commit/39b6e0af80aae93e2dd0bbf7bb5cfcbff4717407)

https://github.com/karrioapi/karrio/blob/da16f3265b68b8d73f3228f0203718d63f5bc36f/.github/workflows/build.yml#L75

Why is a 'version' being set to a URL?

I'm not sure what would be the correct value...

**Comment by danh91** [comment]
Yup, that's weird, indeed. Looks like a mistake. 
It's not even a valid environment variable.

**Comment by danh91** [comment]
Fix with commit https://github.com/karrioapi/karrio/commit/2bd71a25db44bf42aec999d01efb30b909ebcfe8
